name: Issue to In Progress

on:
  issues:
    types: [assigned]



jobs:
    move_issue_to_in_progress:
        runs-on: ubuntu-latest
        steps:
            - name: Move issue to in progress
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                issue_number=${{ github.event.issue.number }}

                card_id=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github.inertia-preview+json" \
                      "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}/projects" |
                      jq -r '.[0].id')
                
                echo "Card ID: $card_id"

                # curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
                #       -H "Accept: application/vnd.github.inertia-preview+json" \
                #       -d '{"position": "top", "column_id": $PROJECT_COLUMN_ID}' \
                #       "https://api.github.com/projects/columns/cards/${card_id}/moves"
                


