name: Test Runner

on: 
    pull_request: 
        branches: main
        

env: 
  SRC_PATH: test
  TEST_PATH: test
    

jobs:        
    test: 
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Setup dotnet '8.0.x'
            uses: actions/setup-dotnet@v3
            with:
                dotnet-version: "8.0.x"

          - name: Restore dotnet
            run: dotnet restore "$SRC_PATH"

          - name: Build dotnet
            run: dotnet build "$SRC_PATH"

          - name: Test dotnet
            run: dotnet test --logger "console" "$TEST_PATH"


